# Generated by Django 3.1.4 on 2020-12-21 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('writing', '0003_notes_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
