# Generated by Django 3.1.4 on 2020-12-21 19:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('writing', '0004_notes_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 12, 21, 12, 9, 14, 136366), null=True),
        ),
    ]
