# Generated by Django 3.1.4 on 2020-12-22 19:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('writing', '0006_auto_20201222_1219'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='parent',
            field=models.TextField(default='Parent'),
        ),
        migrations.AddField(
            model_name='notes',
            name='title',
            field=models.TextField(default='A neat Title'),
        ),
        migrations.AlterField(
            model_name='notes',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 12, 22, 12, 22, 35, 365471), null=True),
        ),
    ]
